---
title: Adept | Fulfilment Services
short_title: Adept
description: We are Adept.
logo: adept-white-logo.svg
lang: en
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
  # posts:
  #   title: News
  #   output: true
baseurl:
url:
markdown: kramdown
phone: 0191 389 8725
email: bd@adeptfulfilment.com
linkedin: https://www.linkedin.com/company/adept-fulfilment/
address:
  address_line_1: 7-8 Fox Cover Industrial Estate
  address_line_2: Admirality Way
  city: Seaham
  county: County Durham
  postcode: SR7 7DN
img_dir: /uploads/
exclude:
  - vendor
  - node_modules
  - gulpfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - github-pages
  - jekyll-redirect-from
  - jekyll-seo-tag
whitelist:
  - jekyll-redirect-from
